spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queues:
      operation: queueDeposit
      transfer: queueTransfer

microservices:
  operation:
    url: http://localhost:8081/beercoin/operation/save
  transfer:
    url: http://localhost:8081/beercoin/transfer/save

amqp:
  maxRetry: 3

server:
  port : ${PORT:5000}