version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 15672" ]
      interval: 5scd
      timeout: 5s
      retries: 5
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
networks:
  mysql-compose-network:
    driver: bridge